import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, MapPin, Check, Star } from "lucide-react";
import MarketplaceSearch from "@/components/search/MarketplaceSearch";

export default function DiscoveryLanding({ kind, children, hasProfiles }: { kind: "coaches" | "venues"; children: React.ReactNode; hasProfiles: boolean }) {
  const coach = kind === "coaches";
  const hero = coach ? "/images/discovery/coaching-session.webp" : "/images/discovery/coastal-venue.webp";
  const editorial = coach ? "/images/discovery/coastal-venue.webp" : "/images/discovery/coaching-session.webp";
  const join = `/signup?next=${encodeURIComponent(`/account/applications/${coach ? "coach" : "venue"}`)}`;
  const container = "mx-auto max-w-7xl px-5 sm:px-8";
  return <main className="bg-white">
    <section className="relative bg-primary text-white">
      <div className="absolute inset-0"><Image src={hero} alt="" fill priority sizes="100vw" className="object-cover object-[65%_45%]" /><div className="absolute inset-0 bg-gradient-to-r from-primary via-primary/75 to-primary/10" /></div>
      <div className={`${container} relative pb-24 pt-16 sm:pb-28 sm:pt-24 lg:py-28`}>
        <div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-accent">{coach ? "A little direction. A different game." : "Your game can take you places."}</p><h1 className="mt-5 text-4xl leading-[1.05] text-white sm:text-6xl">{coach ? <>Find your coach.<br /><span className="text-accent">Own your progress.</span></> : <>Great courts.<br /><span className="text-accent">Even better days.</span></>}</h1><p className="mt-6 max-w-md text-base leading-7 text-white/85">{coach ? "From your first rally to your next competition, find coaching that meets you where you are." : "Discover somewhere worth playing. Explore padel venues, meet local coaches and make more of your time on court."}</p><Link href={`/${kind}?view=results`} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-white underline underline-offset-4">Explore all {kind}<ArrowUpRight className="h-4 w-4" /></Link></div>
      </div>
      <div className="absolute inset-x-0 bottom-0 z-20 translate-y-1/2 px-5 text-primary"><MarketplaceSearch defaultMode={kind} variant="listing" /></div>
    </section>

    <section className={`${container} grid items-center gap-10 pb-16 pt-24 md:grid-cols-2 lg:gap-20 lg:pb-24 lg:pt-32`}>
      <div className="relative aspect-[5/4] overflow-hidden rounded-[28px]"><Image src={editorial} alt={coach ? "Illustrative coastal padel courts and clubhouse" : "Illustrative coaching session on a padel court"} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /><span className="absolute bottom-4 left-4 rounded-full bg-white/90 px-3 py-1 text-xs text-primary">More than a place to play</span></div>
      <div><p className="text-xs font-semibold uppercase tracking-[.15em] text-primary/50">This is Padel Pathways</p><h2 className="mt-4 text-3xl sm:text-4xl">{coach ? "The right person can change your game." : "Find your court. Find your people."}</h2><p className="mt-5 text-base leading-7 text-primary/70">{coach ? "We bring coach profiles, training locations and session requests together, so you can spend less time searching and more time improving." : "Padel Pathways connects players with places to train and people to learn from. Start with a destination, get to know a venue and discover the coaching around it."}</p><ul className="mt-6 space-y-3">{(coach ? ["Compare coaching experience and areas of focus", "Find coaching for your level and goals", "Keep session requests together in your account"] : ["Explore venues by city or country", "Compare courts, settings and facilities", "Discover coaches linked to the places you like"]).map(text => <li key={text} className="flex items-start gap-3 text-sm"><Check className="h-5 w-5 shrink-0" />{text}</li>)}</ul></div>
    </section>

    {!coach ? <section className="bg-surface py-16"><div className={container}><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-primary/50">A change of scene</p><h2 className="mt-3 text-3xl sm:text-4xl">Where will you play next?</h2></div><p className="max-w-sm text-sm leading-6 text-primary/65">Explore these Spanish destinations. Availability depends on the venues currently listed.</p></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{[{city:"Marbella",caption:"Your next coastal court",colour:"bg-primary text-white"},{city:"Barcelona",caption:"Bring padel to your city break",colour:"bg-[#afd0db] text-primary"},{city:"Alicante",caption:"Make more time for your game",colour:"bg-accent text-primary"}].map(({city,caption,colour}) => <Link key={city} href={`/venues?location=${encodeURIComponent(city)}`} className={`group relative min-h-48 overflow-hidden rounded-2xl p-7 ${colour}`}><MapPin className="h-7 w-7 opacity-70" /><h3 className="mt-7 text-2xl !text-inherit">{city}</h3><p className="mt-2 text-sm opacity-75">{caption}</p><ArrowUpRight className="absolute right-6 top-7 h-6 w-6 transition group-hover:-translate-y-1 group-hover:translate-x-1" /></Link>)}</div></div></section> : null}

    {hasProfiles ? <section className={`${container} py-16`}><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><h2 className="text-3xl">{coach ? "Meet the coaches" : "Explore our venue community"}</h2><Link href={`/${kind}?view=results`} className="text-sm font-semibold underline">View all {kind}</Link></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{children}</div></section> : null}

    <section className="bg-primary py-16 text-white sm:py-20"><div className={container}><p className="text-xs font-semibold uppercase tracking-[.15em] text-accent">From browsing to playing</p><h2 className="mt-3 text-3xl text-white sm:text-4xl">Your next session starts here.</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{(coach ? [{title:"Find your fit",body:"Search by location or goal. Explore the coach’s experience, approach and player levels."},{title:"Choose a session",body:"Check available coaching slots and send a request. Your coach confirms the arrangements."},{title:"Build your progress",body:"Manage your bookings and leave a verified coach review after a completed session."}] : [{title:"Explore a destination",body:"Search by location or venue name, then narrow your options by courts and playing conditions."},{title:"Get to know the venue",body:"Read the profile, look at facilities and discover the coaches connected to the club."},{title:"Plan your time on court",body:"Request available coaching sessions. Check court-only booking arrangements directly with the venue."}]).map((item,i) => <div key={item.title} className="border-t border-white/25 pt-6"><span className="text-3xl font-semibold text-accent">0{i+1}</span><h3 className="mt-5 text-xl text-white">{item.title}</h3><p className="mt-3 text-sm leading-7 text-white/75">{item.body}</p></div>)}</div></div></section>

    <section className={`${container} grid items-center gap-10 py-16 md:grid-cols-2 lg:gap-20 lg:py-24`}><div><p className="text-xs font-semibold uppercase tracking-[.15em] text-primary/50">Know what you are choosing</p><h2 className="mt-4 text-3xl sm:text-4xl">{coach ? "A clearer picture before you book." : "What makes a venue right for you?"}</h2><p className="mt-5 text-base leading-7 text-primary/70">{coach ? "A profile should help you make a decision. Look for relevant experience, the levels a coach teaches and sessions that work with your schedule." : "Our directory brings venue information into one place. Venue applications are reviewed before publication; published profiles help you compare the details that matter to your visit."}</p><div className="mt-6 rounded-2xl bg-surface p-6"><Star className="h-6 w-6" /><h3 className="mt-3 text-lg">{coach ? "Reviews tied to real sessions" : "Look beyond a star rating"}</h3><p className="mt-2 text-sm leading-6 text-primary/70">{coach ? "Players can review completed bookings across coaching quality, player progress and value for money." : "Check the court setting, facilities, location and coaching options. Confirm current access and arrangements with the venue before travelling."}</p></div></div><div className="relative aspect-[5/4] overflow-hidden rounded-[28px]"><Image src={hero} alt={coach ? "Illustrative coach explaining a padel grip" : "Illustrative Mediterranean padel venue"} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div></section>

    <section className="bg-accent py-16 sm:py-20"><div className={`${container} grid items-center gap-10 md:grid-cols-[1.4fr_1fr]`}><div><p className="text-xs font-semibold uppercase tracking-[.15em]">{coach ? "For coaches" : "For venues"}</p><h2 className="mt-4 text-3xl sm:text-4xl">{coach ? "Your expertise. A wider community." : "Your club deserves to be discovered."}</h2><p className="mt-5 max-w-xl text-base leading-7">{coach ? "Build a professional profile, connect your training venues and manage coaching requests in one workspace." : "Showcase your courts and facilities, connect with coaches and help players understand what your venue offers."}</p><Link href={join} className="mt-7 inline-flex items-center gap-3 rounded-full bg-primary px-7 py-4 text-sm font-semibold text-accent">{coach ? "Create your coach account" : "Register your venue"}<ArrowUpRight className="h-4 w-4" /></Link></div><ol className="space-y-5">{["Create your account", "Complete your profile and submit for review", "Manage your profile after approval"].map((text,i) => <li key={text} className="flex gap-4 border-t border-primary/20 pt-5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-primary text-sm text-accent">{i+1}</span><p className="pt-1 text-sm font-semibold">{text}</p></li>)}</ol></div></section>
    <div className={`${container} py-5 text-xs text-primary/45`}>Editorial imagery is illustrative. View individual profiles for venue and coach photographs.</div>
  </main>;
}
