-- Use the published allow-list projections for player-visible publication checks.
-- Keep invoker rights and all booking/ownership/availability checks unchanged.
CREATE OR REPLACE FUNCTION private.prepare_coach_booking_request()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare caller_id uuid:=(select auth.uid()); relationship_record public.coach_venues%rowtype; settings_record public.coach_venue_availability_settings%rowtype; coach_publication text; venue_publication text; resolved_price record; caller_is_coach_member boolean:=false; caller_is_admin boolean:=false; status_changed boolean:=false;
begin
if caller_id is null then raise exception 'Authentication is required.' using errcode='42501'; end if; caller_is_admin:=private.is_current_user_admin();
if tg_op='INSERT' then
 select * into relationship_record from public.coach_venues where id=new.coach_venue_id;
 if relationship_record.id is null or relationship_record.status<>'active' then raise exception 'Booking requests require an active coach venue relationship.' using errcode='23514'; end if;
 select c.publication_status,v.publication_status into coach_publication,venue_publication from public.coach_public_profiles c,public.venue_public_profiles v where c.id=relationship_record.coach_id and v.id=relationship_record.venue_id;
 if coach_publication is distinct from 'published' or venue_publication is distinct from 'published' then raise exception 'Booking requests require a published coach and venue.' using errcode='23514'; end if;
 select * into settings_record from public.coach_venue_availability_settings where coach_venue_id=new.coach_venue_id;
 if settings_record.coach_venue_id is null or settings_record.is_public is not true then raise exception 'This coach is not accepting public booking requests at this venue.' using errcode='23514'; end if;
 if new.requester_user_id<>caller_id then raise exception 'The requester cannot be changed.' using errcode='42501'; end if;
 if not private.is_valid_availability_slot(new.coach_venue_id,new.starts_at,new.ends_at) then raise exception 'The selected time is no longer available.' using errcode='23514'; end if;
 select * into resolved_price from private.resolve_public_slot_price(new.coach_venue_id,new.starts_at,new.ends_at);
 new.coach_id:=relationship_record.coach_id; new.venue_id:=relationship_record.venue_id; new.timezone:=settings_record.timezone; new.status:='requested'; new.price_amount_minor:=resolved_price.price_amount_minor; new.currency:=resolved_price.currency; new.pricing_source:=resolved_price.pricing_source; new.responded_at:=null; new.responded_by_user_id:=null; new.cancelled_at:=null; new.cancelled_by_user_id:=null; new.completed_at:=null; new.updated_at:=now(); return new;
end if;
if new.id is distinct from old.id or new.coach_venue_id is distinct from old.coach_venue_id or new.coach_id is distinct from old.coach_id or new.venue_id is distinct from old.venue_id or new.requester_user_id is distinct from old.requester_user_id or new.starts_at is distinct from old.starts_at or new.ends_at is distinct from old.ends_at or new.timezone is distinct from old.timezone or new.requester_name is distinct from old.requester_name or new.requester_email is distinct from old.requester_email or new.requester_phone is distinct from old.requester_phone or new.player_level is distinct from old.player_level or new.message is distinct from old.message or new.price_amount_minor is distinct from old.price_amount_minor or new.currency is distinct from old.currency or new.pricing_source is distinct from old.pricing_source or new.created_at is distinct from old.created_at then raise exception 'Booking request details cannot be changed after submission.' using errcode='42501'; end if;
select exists(select 1 from public.coach_memberships where coach_id=old.coach_id and user_id=caller_id) into caller_is_coach_member; status_changed:=new.status is distinct from old.status; if not status_changed then new.updated_at:=now(); return new; end if;
case old.status when 'requested' then if new.status in ('accepted','declined') then if not caller_is_coach_member and not caller_is_admin then raise exception 'Only the coach may respond to this booking request.' using errcode='42501'; end if; if new.status='accepted' and not private.is_valid_availability_slot(old.coach_venue_id,old.starts_at,old.ends_at) then raise exception 'The selected time is no longer available.' using errcode='23514'; end if; new.responded_at:=now(); new.responded_by_user_id:=caller_id; new.cancelled_at:=null; new.cancelled_by_user_id:=null; new.completed_at:=null; elsif new.status='cancelled' then if caller_id<>old.requester_user_id and not caller_is_coach_member and not caller_is_admin then raise exception 'Only the requester or coach may cancel this request.' using errcode='42501'; end if; new.cancelled_at:=now(); new.cancelled_by_user_id:=caller_id; new.responded_at:=null; new.responded_by_user_id:=null; new.completed_at:=null; else raise exception 'Invalid transition from requested.' using errcode='23514'; end if; when 'accepted' then if new.status='cancelled' then if caller_id<>old.requester_user_id and not caller_is_coach_member and not caller_is_admin then raise exception 'Only the requester or coach may cancel this session.' using errcode='42501'; end if; new.cancelled_at:=now(); new.cancelled_by_user_id:=caller_id; new.completed_at:=null; elsif new.status='completed' then if not caller_is_coach_member and not caller_is_admin then raise exception 'Only the coach may mark the session complete.' using errcode='42501'; end if; if old.ends_at>now() then raise exception 'A future session cannot be marked complete.' using errcode='23514'; end if; new.completed_at:=now(); new.cancelled_at:=null; new.cancelled_by_user_id:=null; else raise exception 'Invalid transition from accepted.' using errcode='23514'; end if; when 'declined','cancelled','completed' then raise exception 'Historical booking requests cannot be changed.' using errcode='23514'; else raise exception 'Unknown booking status.' using errcode='23514'; end case;
new.updated_at:=now(); return new; end;$function$

